GRID_STEP = 0.11

TABLE_CENTER = (-0.1, -0.2)
FOOD_STORAGE_CENTER = (-0.25, 0.25)
DISH_STORAGE_CENTER = (-0.05, 0.25)

TABLE_OFFSETS = (
    (-GRID_STEP, -GRID_STEP),
    (-GRID_STEP, 0.0),
    (-GRID_STEP, GRID_STEP),
    (0.0, -GRID_STEP),
    (0.0, 0.0),
    (0.0, GRID_STEP),
    (GRID_STEP, -GRID_STEP),
    (GRID_STEP, 0.0),
    (GRID_STEP, GRID_STEP),
)

STORAGE_OFFSETS = (
    (0.0, GRID_STEP),
    (0.0, 0.0),
    (0.0, -GRID_STEP),
)

TABLE_DISTANCE_THRESHOLD = 0.2
STORAGE_DISTANCE_THRESHOLD = 0.16
